### ISSUE TITLE
Allow types of any kind as tags

### ISSUE THREAD

**Issue by ElvishJerricco** [int-index/ether#15]
I'm writing a library that abstracts over some `f :: * -> *`, and `f` makes the most sensible type for the tag. Attempting to use `f` as the tag for, say, `MonadState`, results in a type error. Simple example:

```haskell
class MyClass s f where
  myMethod :: MonadState f s m => f a -> m a
```

Granted, in this case, I can just use `f ()` as the tag instead of `f`, but I don't fee like that's a real solution. It would be nice if I could just use `f` on its own, and manually pass `Proxy :: Proxy f` to the StateT methods.

**Comment by int-index** [comment]
Try with the latest version! :)

Poly-kinded tags are one of the features in the `4.0` (install via Stackage nightly).

**Comment by ElvishJerricco** [comment]
Oh cool! My bad, forgot to check my version.

**Comment by ElvishJerricco** [comment]
Yep, works just fine! Thanks!

**Comment by int-index** [comment]
Great!
