### ISSUE TITLE
Add documentation link to Hackage docs / description.

### ISSUE THREAD

**Issue by stephen-smith** [int-index/ether#16]
int_index (on reddit):

> The introduction covers them: https://int-index.github.io/ether/

> I should probably add this link to the package description.

Creating an issue so it doesn't get forgotten.

**Comment by int-index** [comment]
I believe I did that a few minutes after posting the comment. Perhaps your browser has cached the Hackage page? Please check again.

**Comment by int-index** [comment]
Closing because the link is certainly in the description:

![image](https://cloud.githubusercontent.com/assets/4061728/14628350/c1eddd7a-0605-11e6-993d-88aebb0be8c4.png)
