### ISSUE TITLE
Add instances for MonadBaseControl and others

### ISSUE THREAD

**Issue by gittywithexcitement** [int-index/ether#4]
Today I found myself needing StateT to have an instance for MonadBaseControl and related type classes. 

The instance definitions are boilerplate and easily defined.

```Haskell
instance MonadTransControl (Ether.StateT tag s) where
    type StT (Ether.StateT tag s) a = (a, s)
    liftWith f = Ether.stateT (Proxy :: Proxy tag) $ \s ->
                   liftM (\x -> (x, s))
                         (f $ \t -> Ether.runStateT (Proxy :: Proxy tag) t s)
    restoreT = Ether.stateT (Proxy :: Proxy tag) . const

instance (MonadBase b m) => MonadBase b (Ether.StateT tag s m) where
  liftBase = liftBaseDefault

instance (MonadBaseControl b m) => MonadBaseControl b (Ether.StateT tag s m) where
  type StM (Ether.StateT tag s m) a = ComposeSt (Ether.StateT tag s) m a
  liftBaseWith = defaultLiftBaseWith
  restoreM     = defaultRestoreM

```

If you're not averse, it would be nice to have these instances for all of the Control.Monad.Trans.Ether.* classes. I'm willing to make a PR and create the other instances.

**Comment by int-index** [comment]
I defined `MonadTransControl` and `MFunctor` instances in another branch. See [here](https://github.com/int-index/ether/blob/trans-lift/src/Control/Monad/Trans/Ether/State/Lazy.hs). I will merge this branch whet I'll figure out a better design for my [https://github.com/int-index/transformers-lift](https://github.com/int-index/transformers-lift) package.

For now you'll have to use orphan instances.

**Comment by gittywithexcitement** [comment]
Ok. Let me know how it goes.

**Comment by int-index** [comment]
`MonadBase`, `MonadControl` and `MonadBaseControl` instances are now in the `master` branch.

**Comment by int-index** [comment]
@gittywithexcitement Please confirm that this indeed fixes your issue.

**Comment by gittywithexcitement** [comment]
@int-index yes, it works for me. Thank you!
