### ISSUE TITLE
Add instances for MonadThrow and MonadCatch

### ISSUE THREAD

**Issue by gittywithexcitement** [int-index/ether#5]
Sorry to bug you again :open_mouth:.  Would you please add `MonadThrow` and `MonadCatch` instances (see http://hackage.haskell.org/package/exceptions-0.8.0.2/docs/Control-Monad-Catch.html#t:MonadCatch)? They are more useful to me than `MonadError`.

**Comment by int-index** [comment]
How is it better than just using `Ether.Implicit.ExceptT SomeException`?

**Comment by int-index** [comment]
@gittywithexcitement Please, feel free to reopen the issue if the fix was not sufficient.
